### PR TITLE
Make python-seco-range compatible with both Python 2 and 3

### PR DESCRIPTION
**Pull request by btilton-gt**
The goal of this is to make python-seco-range compatible with Python 3 while
still remaining compatible with Python 2.

### CODE REVIEW

**Comment by btilton-gt** [comment]
Opened this PR in case any other poor souls out there still need python-seco-range now that Python 2 is EOL

**Comment by btilton-gt** [comment]
For anyone else that finds this, I'm sorry you're also still stuck using Range. I've also uploaded a purely Python 3 version of python-seco-range to PyPi named python3-seco-range. It probably has bugs but feel free to make PRs against my fork I guess. Good luck and god-speed.

**Comment by nmeyerhans** [comment]
Merged! Is range really that horrible for you? It's been a while, but I loved it when I was using it.

**Comment by btilton-gt** [comment]
@nmeyerhans Wow, I actually didn't expect my PR to get merged, thanks!

Range itself is not horrible, it actually works quite well. The problem is that it's not maintained as evidenced by my PR being the first commit in 6 and half years. And there is very limited documentation (unless there's documentation somewhere I haven't found).

**Pull request merged**
